### PR TITLE
postgresql 9.4 compatibility changes

### PR DESCRIPTION
**Pull request by ahsancse**

### CODE REVIEW

**Comment by ruwanta** [comment]
Thank you for contribution.
However postgres 9.4 is EoL as of now.
Better to do this change on a forked repository or a branch which is only targeted for older version of postgress.

**Comment by vinok88** [comment]
Hi Ruwan,
This pull request makes it compatible with Postgres 9.4 while keeping the compatibility of newer versions as well. 
Is it possible to merge this? IF we go to a separate branch, we may miss newer changes to the tool.

**Comment by ruwanta** [comment]
PGQSL 9.4 is not in the IS support matrix. adding this support means we need to keep supporting old databases. Hence adding this will cause many more issues in future.

**Comment by madurangasiriwardena** [comment]
Closing the PR based on the above discussions.

**Pull request closed without merging**
